import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Toaster } from "sonner";

import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import { DemoNavbar } from "@/components/demo/DemoNavbar";
import { DemoFooter } from "@/components/demo/DemoFooter";
import { Providers } from "@/providers";
import { isDemoMode } from "@/lib/demo";
import "@/styles/globals.css";
import "@/styles/colors.css";
import "@/styles/animations.css";
import "@/styles/demo-lowes.css";

export const metadata: Metadata = {
  title: isDemoMode ? "Lowe's Home Improvement" : "Ecommerce Template",
  description: isDemoMode
    ? "Find everything you need for your next home improvement project"
    : "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" {...(isDemoMode ? { "data-demo": "lowes" } : {})}>
      <body className={GeistSans.className}>
        <Providers>
          {isDemoMode ? <DemoNavbar /> : <Navbar />}
          <main className="pointer-events-auto">
            {children}
            <Toaster position="bottom-right" />
            <Analytics />
            <SpeedInsights />
          </main>
          {isDemoMode ? <DemoFooter /> : <Footer />}
        </Providers>
      </body>
    </html>
  );
}
